// Fetch wrappers for the four backend endpoints (spec §6).
//
// The base URL is injected at build time by the GitHub Actions workflow
// (VITE_API_BASE_URL, a repo variable pointing at the Render service). It falls back
// to a local backend so `npm run dev` works with no configuration.

const BASE = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '')

export class ApiError extends Error {
  constructor(message, status) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

async function failure(response) {
  // FastAPI reports validation problems in `detail`, which may be a string or a list.
  let detail = `Request failed (HTTP ${response.status})`
  try {
    const body = await response.json()
    if (typeof body.detail === 'string') detail = body.detail
    else if (body.detail) detail = JSON.stringify(body.detail)
  } catch {
    /* not JSON -- keep the status-based message */
  }
  return new ApiError(detail, response.status)
}

// Render's free tier sleeps after inactivity and takes ~30s to wake (§9.11). Calling
// this on page load means the teacher's first real request is not the one that waits.
export async function pingHealth({ timeoutMs = 45000 } = {}) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const response = await fetch(`${BASE}/api/health`, { signal: controller.signal })
    return response.ok
  } catch {
    return false
  } finally {
    clearTimeout(timer)
  }
}

export async function fetchDefaults() {
  const response = await fetch(`${BASE}/api/defaults`)
  if (!response.ok) throw await failure(response)
  return response.json()
}

// Templates are generated by the backend rather than client-side, so the column
// headers can never drift from what the parser expects.
export async function downloadTemplate(kind, classInfo) {
  const response = await fetch(`${BASE}/api/templates/${kind}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: kind === 'marks' ? JSON.stringify(classInfo) : null,
  })
  if (!response.ok) throw await failure(response)
  saveBlob(await response.blob(), `${kind}_template.xlsx`)
}

// Loads the whole class into the dashboard: every student with their marks, derived
// values and signature status.
export async function requestPreview({ roster, marks, signatureSheet, classInfo }) {
  const form = new FormData()
  form.append('roster', roster)
  form.append('marks', marks)
  // class_info is a JSON *string* inside multipart, not a JSON body (§9.12).
  form.append('class_info', JSON.stringify(classInfo))
  if (signatureSheet) form.append('signature_sheet', signatureSheet)

  const response = await fetch(`${BASE}/api/preview`, { method: 'POST', body: form })
  if (!response.ok) throw await failure(response)
  return response.json()
}

// Re-derives one student after an edit. Deliberately a round trip: Remarks, AR
// References, the best-N-of-M total and the feedback band are computed by the same
// code that renders the PDF, so the browser can never disagree with the document.
export async function scoreStudent({ classInfo, roll, name, scores }) {
  const response = await fetch(`${BASE}/api/score`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ classInfo, roll, name, scores }),
  })
  if (!response.ok) throw await failure(response)
  return response.json()
}

// Fetches a student's signature so it can be shown before generating. Returns an
// object URL, or null with the reason when the Drive link is not usable.
export async function fetchSignatureImage(driveId) {
  const response = await fetch(`${BASE}/api/signature`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ driveId }),
  })
  if (!response.ok) {
    const exc = await failure(response)
    return { url: null, error: exc.message }
  }
  return { url: URL.createObjectURL(await response.blob()), error: null }
}

export async function generateOne({
  classInfo,
  student,
  driveId,
  teacherSignature,
  collegeStamp,
  studentSignature,
}) {
  const form = new FormData()
  form.append('class_info', JSON.stringify(classInfo))
  form.append('student', JSON.stringify(student))
  if (driveId) form.append('drive_id', driveId)
  if (teacherSignature) form.append('teacher_signature', teacherSignature)
  if (collegeStamp) form.append('college_stamp', collegeStamp)
  if (studentSignature) form.append('student_signature', studentSignature)

  const response = await fetch(`${BASE}/api/generate-one`, { method: 'POST', body: form })
  if (!response.ok) throw await failure(response)

  const blob = await response.blob()
  const name =
    filenameFrom(response.headers.get('Content-Disposition')) ||
    `${student.roll}.pdf`
  saveBlob(blob, name)
  return {
    filename: name,
    signatureStatus: response.headers.get('X-Signature-Status') || '',
  }
}

export async function requestGenerate({
  roster,
  marks,
  teacherSignature,
  collegeStamp,
  signatureSheet,
  overrideZip,
  classInfo,
}) {
  const form = new FormData()
  form.append('roster', roster)
  form.append('marks', marks)
  form.append('class_info', JSON.stringify(classInfo))
  if (teacherSignature) form.append('teacher_signature', teacherSignature)
  if (collegeStamp) form.append('college_stamp', collegeStamp)
  if (signatureSheet) form.append('signature_sheet', signatureSheet)
  if (overrideZip) form.append('student_signatures_zip', overrideZip)

  const response = await fetch(`${BASE}/api/generate`, { method: 'POST', body: form })
  if (!response.ok) throw await failure(response)

  const blob = await response.blob()
  const name =
    filenameFrom(response.headers.get('Content-Disposition')) ||
    `Assessment_Reports_${new Date().toISOString().slice(0, 10)}.zip`
  saveBlob(blob, name)
  return { filename: name, size: blob.size, blob }
}

function filenameFrom(disposition) {
  if (!disposition) return null
  const match = /filename="?([^"]+)"?/.exec(disposition)
  return match ? match[1] : null
}

export function saveBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  // Revoke on the next tick; revoking immediately can cancel the download in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

// Reads manifest.json back out of the downloaded ZIP so issues can be shown after the
// download completes (§8 item 5).
//
// Done by hand rather than with a ZIP library: it is one small file out of one archive,
// and DecompressionStream covers the only compression method the backend uses. Entries
// are DEFLATE-compressed, so scanning the archive for plain text would not find it.
export async function readManifest(blob) {
  try {
    const bytes = new Uint8Array(await blob.arrayBuffer())
    const view = new DataView(bytes.buffer)

    // The End of Central Directory record sits at the end, after an optional comment.
    let eocd = -1
    for (let i = bytes.length - 22; i >= 0 && i > bytes.length - 65558; i -= 1) {
      if (view.getUint32(i, true) === 0x06054b50) {
        eocd = i
        break
      }
    }
    if (eocd === -1) return null

    const entryCount = view.getUint16(eocd + 10, true)
    let pointer = view.getUint32(eocd + 16, true)
    const decoder = new TextDecoder()

    for (let entry = 0; entry < entryCount; entry += 1) {
      if (view.getUint32(pointer, true) !== 0x02014b50) return null
      const method = view.getUint16(pointer + 10, true)
      const compressedSize = view.getUint32(pointer + 20, true)
      const nameLength = view.getUint16(pointer + 28, true)
      const extraLength = view.getUint16(pointer + 30, true)
      const commentLength = view.getUint16(pointer + 32, true)
      const localOffset = view.getUint32(pointer + 42, true)
      const name = decoder.decode(bytes.subarray(pointer + 46, pointer + 46 + nameLength))

      if (name === 'manifest.json') {
        // The local header repeats the name/extra lengths, and they can differ from
        // the central directory's, so read them from the local header itself.
        const localNameLength = view.getUint16(localOffset + 26, true)
        const localExtraLength = view.getUint16(localOffset + 28, true)
        const start = localOffset + 30 + localNameLength + localExtraLength
        const data = bytes.subarray(start, start + compressedSize)
        if (method === 0) return JSON.parse(decoder.decode(data))
        if (method === 8) {
          const stream = new Blob([data])
            .stream()
            .pipeThrough(new DecompressionStream('deflate-raw'))
          return JSON.parse(await new Response(stream).text())
        }
        return null
      }
      pointer += 46 + nameLength + extraLength + commentLength
    }
  } catch {
    /* the manifest is a convenience; never break the download over it */
  }
  return null
}
